/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ittimfn.sample.jgit;

import java.io.IOException;
import java.nio.file.Path;
import java.nio.file.Paths;

import org.eclipse.jgit.api.errors.GitAPIException;
import org.eclipse.jgit.api.errors.InvalidRemoteException;
import org.eclipse.jgit.api.errors.TransportException;

import ittimfn.sample.jgit.controller.remote.ListBranchesController;
import ittimfn.sample.jgit.enums.ApplicationPropertiesEnum;
import ittimfn.sample.jgit.enums.AuthPropertiesEnum;

public class App {

    private static final String RESOURCES_HOME = Paths.get(System.getProperty("user.dir"),  "src", "main", "resources").toString();
    private static final Path APPLICATION_PROPERTIES = Paths.get(RESOURCES_HOME, "application.properties");
    private static final Path AUTH_PROPERTIES = Paths.get(RESOURCES_HOME, "auth.properties");

    public String getGreeting() {
        return "Hello World!";
    }

    public void exec(String[] args) throws InvalidRemoteException, TransportException, GitAPIException {
        new ListBranchesController().print();
    }

    public static void main(String[] args) throws IOException, InvalidRemoteException, TransportException, GitAPIException {
        ApplicationPropertiesEnum.load(APPLICATION_PROPERTIES);
        AuthPropertiesEnum.load(AUTH_PROPERTIES);

        new App().exec(args);
    }
}
